.\"{{{}}}
.\"{{{ Title
.TH ILMSCLI 1 "Ilms Client Manual"

.\"}}}

.\"{{{ Name
.SH NAME
ilmscli - ilms client

.\"}}}

.\"{{{ Synopsis
.SH SYNOPSIS
.B ./ilmscli
.br
.BR IP
.BR IP_ADDRESS
.br
.BR REG
.BR ID
.BR [LOC]
.br
.BR SET
.BR ID
.BR LOC
.br
.BR GET
.BR ID
.br
.BR REP
.BR ID
.BR LOC
.br
.BR SUB
.BR ID
.BR LOC
.br
.BR DELETE
.BR ID
.br
.BR EXIT

.\"}}}

.\"{{{ Description
.SH DESCRIPTION
.B ilmscli
ilms cli

.\"}}}
